package com.cbms.model.entity;

// Generated Jan 13, 2016 10:40:11 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", schema = "public")
public class Customer implements java.io.Serializable {

	private int custId;
	private String name;
	private String address;
	private String phoneOffice;
	private String phoneMobile;
	private String skype;
	private String viber;
	private String email;
	private String nic;
	private String country;
	private String city;
	private Date addedDate;
	private String addedBy;
	private Short statCode;
	private Set<SaleInvHeader> saleInvHeaders = new HashSet<SaleInvHeader>(0);

	public Customer() {
	}

	public Customer(int custId, String name, String phoneMobile) {
		this.custId = custId;
		this.name = name;
		this.phoneMobile = phoneMobile;
	}

	public Customer(int custId, String name, String address, String phoneOffice, String phoneMobile, String skype, String viber, String email, String nic, String country, String city, Date addedDate, String addedBy, Short statCode,
			Set<SaleInvHeader> saleInvHeaders) {
		this.custId = custId;
		this.name = name;
		this.address = address;
		this.phoneOffice = phoneOffice;
		this.phoneMobile = phoneMobile;
		this.skype = skype;
		this.viber = viber;
		this.email = email;
		this.nic = nic;
		this.country = country;
		this.city = city;
		this.addedDate = addedDate;
		this.addedBy = addedBy;
		this.statCode = statCode;
		this.saleInvHeaders = saleInvHeaders;
	}

	@SequenceGenerator(name = "customer_seq", sequenceName = "customer_seq")
	@Id
	@GeneratedValue(generator = "customer_seq")
	@Column(name = "cust_id", unique = true, nullable = false)
	public int getCustId() {
		return this.custId;
	}

	public void setCustId(int custId) {
		this.custId = custId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone_office", length = 15)
	public String getPhoneOffice() {
		return this.phoneOffice;
	}

	public void setPhoneOffice(String phoneOffice) {
		this.phoneOffice = phoneOffice;
	}

	@Column(name = "phone_mobile", nullable = false, length = 15)
	public String getPhoneMobile() {
		return this.phoneMobile;
	}

	public void setPhoneMobile(String phoneMobile) {
		this.phoneMobile = phoneMobile;
	}

	@Column(name = "skype", length = 20)
	public String getSkype() {
		return this.skype;
	}

	public void setSkype(String skype) {
		this.skype = skype;
	}

	@Column(name = "viber", length = 20)
	public String getViber() {
		return this.viber;
	}

	public void setViber(String viber) {
		this.viber = viber;
	}

	@Column(name = "email", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "nic", length = 15)
	public String getNic() {
		return this.nic;
	}

	public void setNic(String nic) {
		this.nic = nic;
	}

	@Column(name = "country", length = 25)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "city", length = 25)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "added_date", length = 13)
	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	@Column(name = "added_by", length = 20)
	public String getAddedBy() {
		return this.addedBy;
	}

	public void setAddedBy(String addedBy) {
		this.addedBy = addedBy;
	}

	@Column(name = "stat_code")
	public Short getStatCode() {
		return this.statCode;
	}

	public void setStatCode(Short statCode) {
		this.statCode = statCode;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "customer")
	public Set<SaleInvHeader> getSaleInvHeaders() {
		return this.saleInvHeaders;
	}

	public void setSaleInvHeaders(Set<SaleInvHeader> saleInvHeaders) {
		this.saleInvHeaders = saleInvHeaders;
	}

}
