package com.cbms.model.entity;

// Generated Jan 13, 2016 10:40:11 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ProductCatalog generated by hbm2java
 */
@Entity
@Table(name = "product_catalog", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "prd_name"))
public class ProductCatalog implements java.io.Serializable {

	private int prdCatlogId;
	private String prdName;
	private String prdCode;
	private String usrDefCode;
	private String description;
	private Double purchasePrice;
	private Double salePrice;
	private Integer qtyInHand;
	private Short shelfLife;
	private String rackCode;
	private Short warranty;
	private Date addedDate;
	private String addedBy;
	private Short statCode;
	private Set<SaleInvDetail> saleInvDetails = new HashSet<SaleInvDetail>(0);

	public ProductCatalog() {
	}

	public ProductCatalog(int prdCatlogId, String prdName, String prdCode) {
		this.prdCatlogId = prdCatlogId;
		this.prdName = prdName;
		this.prdCode = prdCode;
	}

	public ProductCatalog(int prdCatlogId, String prdName, String prdCode, String usrDefCode, String description, Double purchasePrice, Double salePrice, Integer qtyInHand, Short shelfLife, String rackCode, Short warranty, Date addedDate, String addedBy, Short statCode,
			Set<SaleInvDetail> saleInvDetails) {
		this.prdCatlogId = prdCatlogId;
		this.prdName = prdName;
		this.prdCode = prdCode;
		this.usrDefCode = usrDefCode;
		this.description = description;
		this.purchasePrice = purchasePrice;
		this.salePrice = salePrice;
		this.qtyInHand = qtyInHand;
		this.shelfLife = shelfLife;
		this.rackCode = rackCode;
		this.warranty = warranty;
		this.addedDate = addedDate;
		this.addedBy = addedBy;
		this.statCode = statCode;
		this.saleInvDetails = saleInvDetails;
	}

	@SequenceGenerator(name = "product_catalog_seq", sequenceName = "product_catalog_seq")
	@Id
	@GeneratedValue(generator = "product_catalog_seq")
	@Column(name = "prd_catlog_id", unique = true, nullable = false)
	public int getPrdCatlogId() {
		return this.prdCatlogId;
	}

	public void setPrdCatlogId(int prdCatlogId) {
		this.prdCatlogId = prdCatlogId;
	}

	@Column(name = "prd_name", unique = true, nullable = false, length = 60)
	public String getPrdName() {
		return this.prdName;
	}

	public void setPrdName(String prdName) {
		this.prdName = prdName;
	}

	@Column(name = "prd_code", nullable = false, length = 30)
	public String getPrdCode() {
		return this.prdCode;
	}

	public void setPrdCode(String prdCode) {
		this.prdCode = prdCode;
	}

	@Column(name = "usr_def_code", length = 10)
	public String getUsrDefCode() {
		return this.usrDefCode;
	}

	public void setUsrDefCode(String usrDefCode) {
		this.usrDefCode = usrDefCode;
	}

	@Column(name = "description", length = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "purchase_price", precision = 17, scale = 17)
	public Double getPurchasePrice() {
		return this.purchasePrice;
	}

	public void setPurchasePrice(Double purchasePrice) {
		this.purchasePrice = purchasePrice;
	}

	@Column(name = "sale_price", precision = 17, scale = 17)
	public Double getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(Double salePrice) {
		this.salePrice = salePrice;
	}

	@Column(name = "qty_in_hand")
	public Integer getQtyInHand() {
		return this.qtyInHand;
	}

	public void setQtyInHand(Integer qtyInHand) {
		this.qtyInHand = qtyInHand;
	}

	@Column(name = "shelf_life")
	public Short getShelfLife() {
		return this.shelfLife;
	}

	public void setShelfLife(Short shelfLife) {
		this.shelfLife = shelfLife;
	}

	@Column(name = "rack_code", length = 10)
	public String getRackCode() {
		return this.rackCode;
	}

	public void setRackCode(String rackCode) {
		this.rackCode = rackCode;
	}

	@Column(name = "warranty")
	public Short getWarranty() {
		return this.warranty;
	}

	public void setWarranty(Short warranty) {
		this.warranty = warranty;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "added_date", length = 13)
	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	@Column(name = "added_by", length = 20)
	public String getAddedBy() {
		return this.addedBy;
	}

	public void setAddedBy(String addedBy) {
		this.addedBy = addedBy;
	}

	@Column(name = "stat_code")
	public Short getStatCode() {
		return this.statCode;
	}

	public void setStatCode(Short statCode) {
		this.statCode = statCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productCatalog")
	public Set<SaleInvDetail> getSaleInvDetails() {
		return this.saleInvDetails;
	}

	public void setSaleInvDetails(Set<SaleInvDetail> saleInvDetails) {
		this.saleInvDetails = saleInvDetails;
	}

}
