package com.cbms.model.entity;

// Generated 14 Jan, 2015 11:51:16 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SaleInvDetail generated by hbm2java
 */
@Entity
@Table(name = "sale_inv_detail", schema = "public")
public class SaleInvDetail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long saleInvDetId;
	private ProductCatalog productCatalog;
	private SaleInvHeader saleInvHeader;
	private BigDecimal unitPrice;
	private Short quantity;
	private BigDecimal total;
	private BigDecimal discount;
	private BigDecimal netTotal;
	private String detRemark;
	private Date addedDate;
	private String addedBy;
	private Short statCode;

	public SaleInvDetail() {
	}

	public SaleInvDetail(long saleInvDetId) {
		this.saleInvDetId = saleInvDetId;
	}

	public SaleInvDetail(long saleInvDetId, ProductCatalog productCatalog, SaleInvHeader saleInvHeader, BigDecimal unitPrice, Short quantity, BigDecimal total, BigDecimal discount, BigDecimal netTotal, String detRemark, Date addedDate, String addedBy, Short statCode) {
		this.saleInvDetId = saleInvDetId;
		this.productCatalog = productCatalog;
		this.saleInvHeader = saleInvHeader;
		this.unitPrice = unitPrice;
		this.quantity = quantity;
		this.total = total;
		this.discount = discount;
		this.netTotal = netTotal;
		this.detRemark = detRemark;
		this.addedDate = addedDate;
		this.addedBy = addedBy;
		this.statCode = statCode;
	}

	@SequenceGenerator(name = "sale_inv_detail_seq", sequenceName = "sale_inv_detail_seq")
	@Id
	@GeneratedValue(generator = "sale_inv_detail_seq")
	@Column(name = "sale_inv_det_id", unique = true, nullable = false)
	public long getSaleInvDetId() {
		return this.saleInvDetId;
	}

	public void setSaleInvDetId(long saleInvDetId) {
		this.saleInvDetId = saleInvDetId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "prd_catlog_id")
	public ProductCatalog getProductCatalog() {
		return this.productCatalog;
	}

	public void setProductCatalog(ProductCatalog productCatalog) {
		this.productCatalog = productCatalog;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sale_inv_id")
	public SaleInvHeader getSaleInvHeader() {
		return this.saleInvHeader;
	}

	public void setSaleInvHeader(SaleInvHeader saleInvHeader) {
		this.saleInvHeader = saleInvHeader;
	}

	@Column(name = "unit_price", precision = 17, scale = 17)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "quantity")
	public Short getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Short quantity) {
		this.quantity = quantity;
	}

	@Column(name = "total", precision = 17, scale = 17)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "discount", precision = 17, scale = 17)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "net_total", precision = 17, scale = 17)
	public BigDecimal getNetTotal() {
		return this.netTotal;
	}

	public void setNetTotal(BigDecimal netTotal) {
		this.netTotal = netTotal;
	}

	@Column(name = "det_remark", length = 150)
	public String getDetRemark() {
		return this.detRemark;
	}

	public void setDetRemark(String detRemark) {
		this.detRemark = detRemark;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "added_date", length = 13)
	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	@Column(name = "added_by", length = 20)
	public String getAddedBy() {
		return this.addedBy;
	}

	public void setAddedBy(String addedBy) {
		this.addedBy = addedBy;
	}

	@Column(name = "stat_code")
	public Short getStatCode() {
		return this.statCode;
	}

	public void setStatCode(Short statCode) {
		this.statCode = statCode;
	}

}
