package com.cbms.model.entity;

// Generated 14 Jan, 2015 11:51:16 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SaleInvHeader generated by hbm2java
 */
@Entity
@Table(name = "sale_inv_header", schema = "public")
public class SaleInvHeader implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int saleInvId;
	private Customer customer;
	private String hdrRemark;
	private Date invDate;
	private BigDecimal grandTotal;
	private Date addedDate;
	private String addedBy;
	private Short statCode;
	private BigDecimal subTotal;

	private Set<SaleInvDetail> saleInvDetails = new HashSet<SaleInvDetail>(0);

	public SaleInvHeader() {
	}

	public SaleInvHeader(int saleInvId, Date invDate) {
		this.saleInvId = saleInvId;
		this.invDate = invDate;
	}

	public SaleInvHeader(int saleInvId, Customer customer,  String hdrRemark, Date invDate, BigDecimal grandTotal, BigDecimal subTotal, Short maxCrPeriod, Date addedDate, String addedBy, Short statCode, Set<SaleInvDetail> saleInvDetails) {
		this.saleInvId = saleInvId;
		this.customer = customer;
		this.hdrRemark = hdrRemark;
		this.invDate = invDate;
		this.grandTotal = grandTotal;
		this.subTotal = subTotal;
		this.addedDate = addedDate;
		this.addedBy = addedBy;
		this.statCode = statCode;
		this.saleInvDetails = saleInvDetails;

	}

	@SequenceGenerator(name = "sale_inv_header_seq", sequenceName = "sale_inv_header_seq")
	@Id
	@GeneratedValue(generator = "sale_inv_header_seq")
	@Column(name = "sale_inv_id", unique = true, nullable = false)
	public int getSaleInvId() {
		return this.saleInvId;
	}

	public void setSaleInvId(int saleInvId) {
		this.saleInvId = saleInvId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cust_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "hdr_remark", length = 150)
	public String getHdrRemark() {
		return this.hdrRemark;
	}

	public void setHdrRemark(String hdrRemark) {
		this.hdrRemark = hdrRemark;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "inv_date", nullable = false, length = 13)
	public Date getInvDate() {
		return this.invDate;
	}

	public void setInvDate(Date invDate) {
		this.invDate = invDate;
	}

	@Column(name = "grand_total", precision = 17, scale = 17)
	public BigDecimal getGrandTotal() {
		return this.grandTotal;
	}

	public void setGrandTotal(BigDecimal grandTotal) {
		this.grandTotal = grandTotal;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "added_date", length = 13)
	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	@Column(name = "added_by", length = 20)
	public String getAddedBy() {
		return this.addedBy;
	}

	public void setAddedBy(String addedBy) {
		this.addedBy = addedBy;
	}

	@Column(name = "stat_code")
	public Short getStatCode() {
		return this.statCode;
	}

	public void setStatCode(Short statCode) {
		this.statCode = statCode;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "saleInvHeader")
	public Set<SaleInvDetail> getSaleInvDetails() {
		return this.saleInvDetails;
	}

	public void setSaleInvDetails(Set<SaleInvDetail> saleInvDetails) {
		this.saleInvDetails = saleInvDetails;
	}

	@Column(name = "sub_total", precision = 17, scale = 17)
	public BigDecimal getSubTotal() {
		return subTotal;
	}

	public void setSubTotal(BigDecimal subTotal) {
		this.subTotal = subTotal;
	}

}
