package com.cbms.model.entity;

// Generated Jan 13, 2016 10:40:11 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysUser generated by hbm2java
 */
@Entity
@Table(name = "sys_user", schema = "public")
public class SysUser implements java.io.Serializable {

	private short id;
	private String userName;
	private String password;
	private String lockState;
	private Short loginFailCount;
	private String userType;
	private String accessType;
	private Date addedDate;
	private String addedBy;
	private Short statCode;

	public SysUser() {
	}

	public SysUser(short id, String userName, String password) {
		this.id = id;
		this.userName = userName;
		this.password = password;
	}

	public SysUser(short id, String userName, String password, String lockState, Short loginFailCount, String userType, String accessType, Date addedDate, String addedBy, Short statCode) {
		this.id = id;
		this.userName = userName;
		this.password = password;
		this.lockState = lockState;
		this.loginFailCount = loginFailCount;
		this.userType = userType;
		this.accessType = accessType;
		this.addedDate = addedDate;
		this.addedBy = addedBy;
		this.statCode = statCode;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	@Column(name = "user_name", nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 300)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "lock_state", length = 1)
	public String getLockState() {
		return this.lockState;
	}

	public void setLockState(String lockState) {
		this.lockState = lockState;
	}

	@Column(name = "login_fail_count")
	public Short getLoginFailCount() {
		return this.loginFailCount;
	}

	public void setLoginFailCount(Short loginFailCount) {
		this.loginFailCount = loginFailCount;
	}

	@Column(name = "user_type", length = 15)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "access_type", length = 10)
	public String getAccessType() {
		return this.accessType;
	}

	public void setAccessType(String accessType) {
		this.accessType = accessType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "added_date", length = 13)
	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	@Column(name = "added_by", length = 20)
	public String getAddedBy() {
		return this.addedBy;
	}

	public void setAddedBy(String addedBy) {
		this.addedBy = addedBy;
	}

	@Column(name = "stat_code")
	public Short getStatCode() {
		return this.statCode;
	}

	public void setStatCode(Short statCode) {
		this.statCode = statCode;
	}

}
