package com.cbms.model.entity;

// Generated Nov 6, 2015 5:51:12 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", schema = "public")
public class UserRole implements java.io.Serializable {
    
	private static final long serialVersionUID = 1L;
	private short id;
	private SysUser sysUser;
	private short moduleId;
	private Short subModuleId;
	private short funcId;
	private String branchCode;
	private Date addedDate;
	private String addedBy;
	private Short statCode;

	public UserRole() {
	}

	public UserRole(short id, SysUser sysUser, short moduleId, short funcId) {
		this.id = id;
		this.sysUser = sysUser;
		this.moduleId = moduleId;
		this.funcId = funcId;
	}

	public UserRole(short id, SysUser sysUser, short moduleId,
			Short subModuleId, short funcId, String branchCode, Date addedDate,
			String addedBy, Short statCode) {
		this.id = id;
		this.sysUser = sysUser;
		this.moduleId = moduleId;
		this.subModuleId = subModuleId;
		this.funcId = funcId;
		this.branchCode = branchCode;
		this.addedDate = addedDate;
		this.addedBy = addedBy;
		this.statCode = statCode;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public SysUser getSysUser() {
		return this.sysUser;
	}

	public void setSysUser(SysUser sysUser) {
		this.sysUser = sysUser;
	}

	@Column(name = "module_id", nullable = false)
	public short getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(short moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "sub_module_id")
	public Short getSubModuleId() {
		return this.subModuleId;
	}

	public void setSubModuleId(Short subModuleId) {
		this.subModuleId = subModuleId;
	}

	@Column(name = "func_id", nullable = false)
	public short getFuncId() {
		return this.funcId;
	}

	public void setFuncId(short funcId) {
		this.funcId = funcId;
	}

	@Column(name = "branch_code", length = 5)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "added_date", length = 13)
	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	@Column(name = "added_by", length = 20)
	public String getAddedBy() {
		return this.addedBy;
	}

	public void setAddedBy(String addedBy) {
		this.addedBy = addedBy;
	}

	@Column(name = "stat_code")
	public Short getStatCode() {
		return this.statCode;
	}

	public void setStatCode(Short statCode) {
		this.statCode = statCode;
	}

}
